services:
  pinternext:
    container_name: pinternext
    image: ghcr.io/remake0992/pinternext:latest
    cap_drop:
      - ALL
    security_opt:
      - no-new-privileges:true
    ports:
     - '8080:8080'
